name: IAM Automation

on:
  push:
    paths:
      - 'data/users.csv'
  workflow_dispatch:

jobs:
  run-iam-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install azure-identity msgraph-sdk pandas

      - name: Run onboarding/offboarding script
        env:
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        run: |
          cd scripts
          python onboarding.py